config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "lists#index"
  resources :lists do
    resources :bookmarks, only: [:show, :new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment,  length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  has_one_attached :poster_url

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new(list_params)
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(list_params)
    @bookmark.list_id = params[:list_id]
    done = @bookmark.save
    if done
      redirect_to list_path(params[:list_id])
    else
      render :new
    end
  end

  def destroy
    del = Bookmark.find(params[:id])
    del.destroy
    redirect_to list_path(del[:list_id])
  end

  private

  def list_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.where(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    done = @list.save
    if done
      redirect_to list_path(@list)
    else
      render :new
    end

  end

  def destroy
    del = List.find(params[:id])
    del.destroy
    redirect_to lists_path
  end


  private


  def list_params
    params.require(:list).permit(:name, :photo)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Add movie to List", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1>New bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Add movie to List", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<h1> Your Lists </h1>
<div class="container">
  <% @lists.each do |list| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
      <p><%= link_to list.name, list %></p>
      <%= button_to "Delete list", list_path(list[:id]), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
  	</div>
  <% end %>
  <%= link_to "Add new list", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file  %>
  <%= f.submit "Create list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<% var1 = cl_image_path @list.photo.key, height: 400, crop: :fill %>
<% var2 = cl_image_tag(@list.photo.key, width: 400, height: 300, crop: :fill) %>
<div class="card-category"  style="height: 200px; background-image: url('<%=var1%>')">
  <h1><%= @list.name  %></h1>
</div>

<div class="container">
  <% @bookmarks.each do |book| %>
    <div class="card-category" style="background-image: url('<%= cl_image_path book.movie.poster_url.key, height: 400, crop: :fill %>')">
      <p><%= book.movie.title  %> </p>
      <%= button_to "Delete movie from list?", bookmark_path(book.id), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>
    </div>
  <%end %>
</div>

<%= render "form", list: @list, bookmark: @bookmark %>
<%= link_to "Back to all lists", lists_path %>